### ISSUE TITLE
Gebruik afkortingen consequent

### ISSUE THREAD

**Issue by StephanyDeMaaijer** [Logius-standaarden/BOMOS-Beheermodel#1]
### Soort

- [ ] Tekstuele fout
- [X] Verbetersuggestie
- [X] Onduidelijke tekst

### Omschrijving

gebruik zelfde afkoring voor verschillende groepen.
In strategie/governance is zowel 1 uitvoeringsorganisatie als 4 BOMOS community de afkorting UG toegedeeld. Klopt dat wel? Als dat wel klopt dan zou ik er een stukje tekst aan wijden dat het om dezelfde groep gaat. 

### Naam

Stephany de Maaijer

### Email

s.demaaijer@ihw.nl

### Organisatie

Informatiehuis Water

**Comment by isik001** [comment]
@StephanyDeMaaijer  dank voor je commentaar, ik heb deze ook aangepast. Ik heb er AG vvan gemaakt en wat tekst toegevoegd.
