### ISSUE TITLE
Onduidelijke zin in strategie

### ISSUE THREAD

**Issue by StephanyDeMaaijer** [Logius-standaarden/BOMOS-Beheermodel#2]
### Soort

- [ ] Tekstuele fout
- [ ] Verbetersuggestie
- [X] Onduidelijke tekst

### Omschrijving

Strategie / organisatiestructuur regel103:
Het voorstel is om met een aantal beheerorganisaties het te formeren:
Waar slaat "het" in deze zin bij het te formeren op? Ik denk 'organisatiestructuur' 
Voorstel voor zin:
Het voorstel is om de organisatiestructuur met een aantal beheerorganisaties te formeren:

### Organisatie

Informatiehuis Water

**Comment by isik001** [comment]
@edwinwisse @StephanyDeMaaijer  dank voor je commentaar, ik heb het aangepast!
