### ISSUE TITLE
Tekst ontbreekt in strategie

### ISSUE THREAD

**Issue by StephanyDeMaaijer** [Logius-standaarden/BOMOS-Beheermodel#3]
### Soort

- [X] Tekstuele fout
- [ ] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

Strategie/ Besluitvorming in regel 138 mist een stuk tekst.

zelfde stuk in regel148 klopt de zin niet: Voor het beheer van BOMOS is nog een eigen budget zoals andere
standaarden of stelsels van Logius beheerd worden. Denk dat het GEEN moet zijn ipv een, gezien de tekst verderop. Zal 'm ook op de andere manier indienen.

### Organisatie

Informatiehuis Water

**Comment by isik001** [comment]
@StephanyDeMaaijer  dank voor je commentaar,  ik heb het aangepast!
