### ISSUE TITLE
Zin over belangenorganisaties loopt niet

### ISSUE THREAD

**Issue by StephanyDeMaaijer** [Logius-standaarden/BOMOS-Beheermodel#4]
### Soort

- [ ] Tekstuele fout
- [ ] Verbetersuggestie
- [X] Onduidelijke tekst

### Omschrijving

Strategie/ belangenorganisaties-betrokkenheid regel 240 snap ik niet:
Belangenorganisaties kunnen optimaal hun achterban bereiken en vertegenwoordigen en daardoor zeer waardevol. 

er mist denk ik een werkwoord in de zin.

### Organisatie

Informatiehuis Water

**Comment by isik001** [comment]
tekst aangepast in: Betrokkenheid van belangenorganisaties is van cruciaal belang  vanwege het feit dat ze vaak optimaal hun achterban kunnen  bereiken en vertegenwoordigen. Alle relevante belangenorganisaties moeten dan ook betrokken zijn, en waar mogelijk  moeten partnerschappen worden gesloten op het gebied van communicatie
