### ISSUE TITLE
Tabel jaarplan niet leesbaar, zin loopt niet

### ISSUE THREAD

**Issue by StephanyDeMaaijer** [Logius-standaarden/BOMOS-Beheermodel#5]
### Soort

- [X] Tekstuele fout
- [ ] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

Tactiek/ community tweede zin loopt niet: 
De leden van de community werken in verschillende beheerorganisaties en kunnen alle informatie m.b.t. de standaard en het beheer daarvan inzien via de website en issues of RFC's melden. 

Tabel (tenminste, dat denk ik dat het moet zijn) in Jaarplan/ontwikkelagenda is niet goed leesbaar. in de gewone versie van het document. Wel leesbaar in de edit file, het is idd een tabel.

### Organisatie

Informatiehuis Water

**Comment by isik001** [comment]
@edwinwisse @sanderke, tabel heb ik toegevoed, wordt het tabel niet goed weergegeven in dynamische omgeving. BIj de repositroies wordt het tabel wel  weergeven 

Zie: 
![image](https://user-images.githubusercontent.com/94606563/191779809-028ee270-a4a5-460a-8287-249b070ef342.png)

**Comment by isik001** [comment]
@StephanyDeMaaijer dankjewel voor je waardevolle feedback, ik heb het in behandling genomen, zie hierboven 👍 :-)

**Comment by sanderke** [comment]
@isik001 Ik zie dat je het tijdelijk hebt opgelost door screenshots te maken van de tabellen in [Tactiek](https://github.com/Logius-standaarden/BOMOS-Beheermodel/blob/develop/ch03_Tactiek.md) en [Operationeel](https://github.com/Logius-standaarden/BOMOS-Beheermodel/blob/develop/ch04_Operationeel.md). Als je het bronbestand (Word?) wil delen zet ik ze wel om naar Markdown.

**Comment by isik001** [comment]
@sanderke sanderke ik stuur bronbestand idd Word via mail.
