### ISSUE TITLE
Gaan RFC's alleen *indien nodig* naar de werkgroep?

### ISSUE THREAD

**Issue by StephanyDeMaaijer** [Logius-standaarden/BOMOS-Beheermodel#6]
### Soort

- [ ] Tekstuele fout
- [ ] Verbetersuggestie
- [X] Onduidelijke tekst

### Omschrijving

Operationeel/Wensen en Eisen.
Laatste alinea staat dit
Dit houdt concreet in dat RFC's die rechtstreeks bij Logius afdeling standaarden worden neergelegd, door een lid van de Uitvoeringsorganisatie en het BOMOS adviesorgaan wordt opgepakt en **indien nodig** doorgespeeld aan de BOMOS werkgroep zodat daar de eerste beoordeling kan plaatsvinden.

Naar mijn mening moet het 'indien nodig' weg, want hoe kan het niet nodig zijn?

Status van de standaard. Tabel is niet als tabel zichtbaar in de tekst.

### Organisatie

Informatiehuis Water

**Comment by isik001** [comment]
issues verwerkt!

**Comment by isik001** [comment]
@StephanyDeMaaijer, dank voor je waardevolle feedback, ik heb beide verwerkt. 

1.Naar mijn mening moet het 'indien nodig' weg, want hoe kan het niet nodig zijn?
2.Status van de standaard. Tabel is niet als tabel zichtbaar in de tekst.
